In [1]:
import pandas as pd
import numpy as np
from sklearn.preprocessing import OneHotEncoder

In [2]:
frame={"colour":["Red","Green","Blue","Yellow"],
    "Target":[0,1,1,0]
   }
df=pd.DataFrame(frame)

In [3]:
df

colour  Target
0     Red       0
1   Green       1
2    Blue       1
3  Yellow       0

In [4]:
hot=OneHotEncoder() # object

In [7]:
ob=hot.fit_transform(df).toarray()

In [8]:
ob # return based on alphabet

array([[0., 0., 1., 0., 1., 0.],
       [0., 1., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 1.],
       [0., 0., 0., 1., 1., 0.]])

In [16]:
pd.DataFrame(ob)

0    1    2    3    4    5
0  0.0  0.0  1.0  0.0  1.0  0.0
1  0.0  1.0  0.0  0.0  0.0  1.0
2  1.0  0.0  0.0  0.0  0.0  1.0
3  0.0  0.0  0.0  1.0  1.0  0.0

In [11]:
hot.inverse_transform(ob)

array([['Red', 0],
       ['Green', 1],
       ['Blue', 1],
       ['Yellow', 0]], dtype=object)

In [12]:
one= OneHotEncoder(drop='first') ## Drop

In [13]:
a=one.fit_transform(df).toarray()
a

array([[0., 1., 0., 0.],
       [1., 0., 0., 1.],
       [0., 0., 0., 1.],
       [0., 0., 1., 0.]])

In [14]:
one.inverse_transform(a)

array([['Red', 0],
       ['Green', 1],
       ['Blue', 1],
       ['Yellow', 0]], dtype=object)

In [15]:
pd.DataFrame(a)

0    1    2    3
0  0.0  1.0  0.0  0.0
1  1.0  0.0  0.0  1.0
2  0.0  0.0  0.0  1.0
3  0.0  0.0  1.0  0.0

In [17]:
done= OneHotEncoder()

In [18]:
done.fit(df)

OneHotEncoder()

In [19]:
b=done.transform(df).toarray()
b

array([[0., 0., 1., 0., 1., 0.],
       [0., 1., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 1.],
       [0., 0., 0., 1., 1., 0.]])

In [20]:
pd.DataFrame(b)

0    1    2    3    4    5
0  0.0  0.0  1.0  0.0  1.0  0.0
1  0.0  1.0  0.0  0.0  0.0  1.0
2  1.0  0.0  0.0  0.0  0.0  1.0
3  0.0  0.0  0.0  1.0  1.0  0.0

In [21]:
done.inverse_transform(b)

array([['Red', 0],
       ['Green', 1],
       ['Blue', 1],
       ['Yellow', 0]], dtype=object)

In [22]:
d={"colour":["Red","Green","Blue","Yellow"],
    
   }
dff=pd.DataFrame(d)

In [23]:
dff

colour
0     Red
1   Green
2    Blue
3  Yellow

In [24]:
do= OneHotEncoder()
c=do.fit_transform(dff).toarray()
c

array([[0., 0., 1., 0.],
       [0., 1., 0., 0.],
       [1., 0., 0., 0.],
       [0., 0., 0., 1.]])

In [25]:
do= OneHotEncoder(drop="first",sparse=False)
c=do.fit_transform(dff)#.toarray()
c

array([[0., 1., 0.],
       [1., 0., 0.],
       [0., 0., 0.],
       [0., 0., 1.]])

In [26]:
pd.get_dummies(dff["colour"])

Blue  Green  Red  Yellow
0     0      0    1       0
1     0      1    0       0
2     1      0    0       0
3     0      0    0       1

In [27]:
# Use One Hot Encoding to change all categorical data to 0 and 1's
X = pd.concat([pd.get_dummies(dff[col], drop_first = True) for col in dff], axis=1, keys=dff.columns)
X.head()

colour           
   Green Red Yellow
0      0   1      0
1      1   0      0
2      0   0      0
3      0   0      1

In [28]:
d={"colour":["Red","Green","Blue"],
    
   }
dff=pd.DataFrame(d)
dff

colour
0    Red
1  Green
2   Blue

In [32]:
X = pd.concat([pd.get_dummies(dff[col], drop_first = False,sparse=False) for col in dff], axis=1, keys=dff.columns)
X.head()

# Based on level

colour          
    Blue Green Red
0      0     0   1
1      0     1   0
2      1     0   0

In [33]:
dt={"colour":["Red","Green","Blue","Yellow"],
    "Target":[0,1,1,0]
   }
df=pd.DataFrame(dt)
df

colour  Target
0     Red       0
1   Green       1
2    Blue       1
3  Yellow       0

In [34]:
df['colour']

0       Red
1     Green
2      Blue
3    Yellow
Name: colour, dtype: object

oen=OneHotEncoder(drop='first')# drop first is to avoid multicollinearity(It means repetition of data)
che_status_enc=oen.fit_transform(df[['colour']])
print(che_status_enc) 

che_status_enc=che_status_enc.toarray()

che_status_enc=pd.DataFrame(che_status_enc) 
# converting to dataframe
che_status_enc=che_status_enc.add_prefix('colour')

df=pd.concat([df,che_status_enc],axis=1) # append to original dataframe


df

In [35]:
one=OneHotEncoder(drop='first')# drop first is to avoid multicollinearity(It means repetition of data)
feature=one.fit_transform(df[['colour']]).toarray()
print(feature) 

feature=pd.DataFrame(feature) 
# converting to dataframe
feature_status=feature.add_prefix('colour_')

df=pd.concat([df,feature_status],axis=1) # append to original dataframe


df

[[0. 1. 0.]
 [1. 0. 0.]
 [0. 0. 0.]
 [0. 0. 1.]]


colour  Target  colour_0  colour_1  colour_2
0     Red       0       0.0       1.0       0.0
1   Green       1       1.0       0.0       0.0
2    Blue       1       0.0       0.0       0.0
3  Yellow       0       0.0       0.0       1.0

In [36]:
dt={"colour":["Red","Green","Blue","Yellow"],
    
    
   }
dft=pd.DataFrame(dt)
dft

colour
0     Red
1   Green
2    Blue
3  Yellow

In [37]:
one=OneHotEncoder()# drop first is to avoid multicollinearity(It means repetition of data)
feature=one.fit_transform(dft[['colour']]).toarray()
print(feature) 

feature=pd.DataFrame(feature) 
# converting to dataframe
feature_status=feature.add_prefix('colour_')

dfc=pd.concat([dft,feature_status],axis=1) # append to original dataframe


dfc

[[0. 0. 1. 0.]
 [0. 1. 0. 0.]
 [1. 0. 0. 0.]
 [0. 0. 0. 1.]]


colour  colour_0  colour_1  colour_2  colour_3
0     Red       0.0       0.0       1.0       0.0
1   Green       0.0       1.0       0.0       0.0
2    Blue       1.0       0.0       0.0       0.0
3  Yellow       0.0       0.0       0.0       1.0

In [38]:
dt={"colour":["Red","Green","Blue","Yellow"],
    "Sex": ["M","M","F","M"]
   }
data=pd.DataFrame(dt)
data

colour Sex
0     Red   M
1   Green   M
2    Blue   F
3  Yellow   M

In [26]:
data.columns.tolist()

['colour', 'Sex']

In [41]:
df = pd.get_dummies(data,drop_first=True)
#col_list = df.columns.tolist()
col_list = df.columns
print(df)

## N-1 to drop the dummy

   colour_Green  colour_Red  colour_Yellow  Sex_M
0             0           1              0      1
1             1           0              0      1
2             0           0              0      0
3             0           0              1      1


In [42]:
new_df = pd.get_dummies(data)
col_list = new_df.columns.tolist()
# handle unknow by using .reindex and .fillna()
new_df = new_df.reindex(columns=col_list).fillna(0.00)
print(new_df)

   colour_Blue  colour_Green  colour_Red  colour_Yellow  Sex_F  Sex_M
0            0             0           1              0      0      1
1            0             1           0              0      0      1
2            1             0           0              0      1      0
3            0             0           0              1      0      1
