In [3]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
from scipy.linalg import eig
from numpy.linalg import eigh

In [31]:
# Creating an Array
data= np.array([
        [ 3,  7],
        [-4, -6],
        [ 7,  8],
        
    ])

In [32]:
data

array([[ 3,  7],
       [-4, -6],
       [ 7,  8]])

In [33]:
df=pd.DataFrame(data,columns=["col1","col2"])
df

col1  col2
0     3     7
1    -4    -6
2     7     8

In [47]:
df.scatter(df["col1"])

AttributeError: 'DataFrame' object has no attribute 'scatter'

In [45]:
df["col1"]

0    3
1   -4
2    7
Name: col1, dtype: int32

In [34]:
#PCA steps:

In [35]:
from sklearn.preprocessing import StandardScaler

In [36]:
sc=StandardScaler()

In [37]:
scdf=sc.fit_transform(df)

In [38]:
scdf[1]

array([-1.31982404, -1.41131261])

In [39]:
scdf.T # transpose of data

array([[ 0.21997067, -1.31982404,  1.09985336],
       [ 0.62725005, -1.41131261,  0.78406256]])

In [40]:
cov_mat=np.cov(scdf.T)

In [41]:
egnvalues, egnvectors = np.linalg.eig(cov_mat)

In [42]:
egnvalues

array([2.93150738, 0.06849262])

In [43]:
egnvectors

array([[ 0.70710678, -0.70710678],
       [ 0.70710678,  0.70710678]])

In [44]:
cov_mat

array([[1.5       , 1.43150738],
       [1.43150738, 1.5       ]])

In [ ]:
principle component